substitutions:
  _REGION: us-central1
  _AR_REPO: tvcb

steps:
# Build webhook-handler
- name: gcr.io/cloud-builders/docker
  dir: src/webhook-handler
  args: ["build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/webhook-handler:${SHORT_SHA}","."]
# Push
- name: gcr.io/cloud-builders/docker
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/webhook-handler:${SHORT_SHA}"]
# Deploy
- name: gcr.io/cloud-builders/gcloud
  args: ["run","deploy","webhook-handler","--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/webhook-handler:${SHORT_SHA}","--region","${_REGION}","--platform","managed"]

# Build trade-executor
- name: gcr.io/cloud-builders/docker
  dir: src/trade-executor
  args: ["build","-t","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/trade-executor:${SHORT_SHA}","."]
# Push
- name: gcr.io/cloud-builders/docker
  args: ["push","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/trade-executor:${SHORT_SHA}"]
# Deploy
- name: gcr.io/cloud-builders/gcloud
  args: ["run","deploy","trade-executor","--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/trade-executor:${SHORT_SHA}","--region","${_REGION}","--platform","managed"]
